name: flutter_project_cm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_marker_popup: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.6
  pdf: ^3.9.0
  printing: ^5.9.0
  mqtt_client: ^10.5.1
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
